### ISSUE TITLE
Error-of-generating-custom-job-for-l4a-crop-type

### ISSUE THREAD

**Issue by HenryHein9** [Sen4CAP/Sen4CAP#3]
Hello Inicola and Sen4Cap,

I am reporting issue here as forum is request timed out again and again. 

I have installed tmux. Tried out the command from that page. Error log is as below. I confirmed that there's enough space. Working and out path are there and have write access permission. 

We have tried mode for "both" and 's2-only'. 

Thanks and Regards,
Henry

`crop-type-wrapper.py -s 2 --season-start 2019-08-24 --season-end 2019-08-24 --working-path /mnt/archive/orchestrator_temp/s4c_l4a/646/2761-s4c-crop-type/ --out-path /mnt/archive/orchestrator_temp/s4c_l4a/646/2762-product-formatter/ --tiles 31UFU --lc 1234 --min-s2-pix 3 --min-s1-pix 1 --best-s2-pix 10 --pa-min 30 --pa-train-h 4000 --pa-train-l 1333 --sample-ratio-h 0.25 --sample-ratio-l 0.75 --smote-target 1000 --smote-k 5 --num-trees 300 --min-node-size 10 --mode s2-only

            select full_path
            from product
            where
                site_id = 2
            and product_type_id = 14
            and created_timestamp <= '2019-08-24'::date
            order by created_timestamp desc
            limit 1
            
Using LPIS from /mnt/archive/lpis/cnetherlands/2019
crop-type-parcels.py -m optical -s 2 --season-start 2019-08-24 --season-end 2019-08-24 --lpis-path /mnt/archive/lpis/cnetherlands/2019 --tiles 31UFU -c /etc/sen2agri/sen2agri.conf

            select site_id,
                   name,
                   full_path,
                   tiles,
                   created_timestamp
            from product
            where satellite_id = 1
              and product_type_id = 1
              and created_timestamp between '2019-08-24'::date and '2019-08-24'::date
              and site_id = 2
            order by site_id, created_timestamp
            
Traceback (most recent call last):
  File "/bin/crop-type-wrapper.py", line 336, in <module>
    main()
  File "/bin/crop-type-wrapper.py", line 273, in main
    os.rename("optical/optical-features.csv", "features/optical-features.csv")
OSError: [Errno 2] No such file or directory
`

**Comment by lnicola** [comment]
It looks like your season has a single day. Is that intentional?

> `--season-start 2019-08-24 --season-end 2019-08-24`

The error probably occurs because there are no products in that time period.

**Comment by HenryHein9** [comment]
Nope. it's not intention. site season starts from Mar 2019 and end in Sept 2019. And this is custom job.

**Comment by lnicola** [comment]
Try using `--season-start 2019-03-01 --season-end 2019-09-30` instead.

Is the season defined correctly in the web interface, while the command line is wrong? Can you post a screenshot of from the site?

**Comment by HenryHein9** [comment]
Looks like it's running. Hope it will generate crop type with prediction. I also wonder why season start and season end are not correct. Please see attached screenshots. 

Thanks and Regards,
Henry 

![image](https://user-images.githubusercontent.com/17008169/88367578-5579a980-cdb6-11ea-9d1d-b192ef8e37af.png)
![image](https://user-images.githubusercontent.com/17008169/88367633-74783b80-cdb6-11ea-87b2-8e5a3f21c158.png)

**Comment by lnicola** [comment]
What if you click "Edit"?

**Comment by HenryHein9** [comment]
Here is the screenshot after clicking on edit.
![image](https://user-images.githubusercontent.com/17008169/88368127-99b97980-cdb7-11ea-8e89-8eb1346ff36c.png)

**Comment by HenryHein9** [comment]
BTW, Wonder why S1 tile info is not showing in that screenshot.

**Comment by lnicola** [comment]
By the way, how did you start the original job? Was it a scheduled one or custom job?

**Comment by HenryHein9** [comment]
it's custom job.

**Comment by lnicola** [comment]
Ah. There's a list of products and it only uses the time interval that covers them, so you usually have to select everything. You might have clicked on one of the products.

> S1 tile info is not showing in that screenshot

I think it's not implemented yet.

**Comment by HenryHein9** [comment]
That's right. I just chose only one generated L2A product. That's the cause, yeah? Thank you for the clarification. I will get back when the process is done.  

Regards,
Henry
