### ISSUE TITLE
GDAL imports

### ISSUE THREAD

**Issue by eftas-gka** [Sen4CAP/Sen4CAP#6]
I came across this error when running the L4B Grassland Mowing job:

`
Traceback (most recent call last):
File "/usr/share/sen2agri/S4C_L4B_GrasslandMowing/Bin/generate_grassland_mowing_input_shp.py", line 11, in <module>
from gdal import gdalconst
ModuleNotFoundError: No module named 'gdal'
`

To fix the error, I replaced the line:

`import gdal`

with

`from osgeo import gdal`

I had to repeat this across multiple files as the all contained the "wrong" import. Same for importing gdalconst.

**Comment by lnicola** [comment]
Thank you. We actually fixed this recently and it's available in 2.0.
